config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'user_profile/:id', to: 'users#show'
  get 'user_profile/:id/edit', to: 'users#edit', as: :edit_user_profile
  patch 'user_profile/:id', to: 'users#update', as: :user_profile
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'my_bookings', to: 'pages#my_bookings' #Bookings summary page for consumer
  get 'my_listings', to: 'pages#my_listings'

  resources :friends do
    resources :bookings , only: [:create, :new]
    member do
      get :bookings #Bookings summary page for provider
    end
  end

  resources :bookings , only: [:show, :edit, :destroy] do
    resources :reviews ,  only: [:new, :create]
   end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :friend
  belongs_to :user
  has_many :reviews, dependent: :destroy

  validates :friend_id, :user_id, :status, :start_time, :end_time, presence: true
  validates :total_price, presence: true, numericality: { only_float: true }
  validates :status, inclusion: { in: %w(pending confirmed complete), message: "%{value} is not a valid status state" }

  validate :end_date_must_be_before_start_date

  # end date and start date right way round
  def end_date_must_be_before_start_date
    return unless start_time && end_time

    errors.add(:end_time, "End Time must be after Start Time") if start_time > end_time
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  has_many :friend_skills, dependent: :destroy
  has_many :skills, through: :friend_skills
  has_many :friend_tags, dependent: :destroy
  has_many :tags, through: :friend_tags
  has_many :bookings
  has_many :reviews, through: :bookings
  belongs_to :user
  has_one_attached :photo
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
    #   trigram ?
    #   dmetaphone ?
    pg_search_scope :global_search, against: [:name, :description],
    associated_against: {
      skills: [:name],tags: [:name]
    },
    using: {
      tsearch: { prefix: true, dictionary: "english" }
    }

  def unavailable_dates
    bookings.pluck(:start_time, :end_time).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/models/friend_skill.rb
class FriendSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :friend
end

app/models/friend_tag.rb
class FriendTag < ApplicationRecord
  belongs_to :friend
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :friend
  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends, dependent: :destroy
  has_many :bookings
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @friend = Friend.find(params[:friend_id])
    @booking = Booking.new
  end

  def create
    @friend = Friend.find(params[:friend_id])
    @booking = Booking.new(booking_params)
    @booking.friend = @friend
    @booking.user = current_user
    if @booking.start_time && @booking.end_time
      @booking.total_price = (@booking.end_time - @booking.start_time) / 60 / 60 * @friend.price
    end
    @booking.status = "pending"
      if @booking.save
        redirect_to booking_path(@booking)
      else
        render 'friends/show'
      end
  end


  def edit
  end

  def destroy
  end

  private

  def booking_params
    params.require(:booking).permit(:friend_id, :user_id, :status, :start_time, :end_time, :total_price)
  end

end
#ADD DELETE AND EDIT BOOKING LATER

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: [:show, :destroy, :edit, :update]
  def index
    @friends = Friend.geocoded
    if params[:query_attributes].present?
      @friends = Friend.global_search(params[:query_attributes])
    end
    @friends = @friends.near(params[:query_location], 5) if (params[:query_location].present? && !@friends.empty?)
    # friends.near(location search)
    @markers = @friends.map do |friend|
    {
      lat: friend.latitude,
      lng: friend.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { friend: friend }),
      image_url: helpers.asset_url('map_icon.png')
    }
    end
  end

  def show
    @booking = Booking.new
    @markers =
      [{
        lat: @friend.latitude,
        lng: @friend.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { friend: @friend }),
        image_url: helpers.asset_url('map_icon.png')
      }]
  end

  def new
    @friend = Friend.new
  end

  def create
    @friend = Friend.new(friend_params)
    @friend.user = current_user
      if @friend.save
        redirect_to friend_path(@friend)
      else
        render 'new'
      end
  end

  def update
    @friend.update(friend_params)
    redirect_to friend_path(@friend)
  end

  def edit
  end

  def destroy
    @friend.destroy
    redirect_to friends_path
  end

private
  def set_friend
    @friend = Friend.find(params[:id])
  end

  def friend_params
    params.require(:friend).permit(:name, :description, :photo, :price, :location)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_friends, only: :my_listings

  def home
  end

  def dashboard
    @booking = current_user.bookings
  end

  def my_bookings
    @bookings = current_user.bookings
  end

  def my_listings; end

  private

  def set_friends
    @friends = current_user.friends
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
      if @review.save
        redirect_to booking_path(@booking)
      else
        render 'new'
      end
   end

   private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :select_user
  # def show
  # end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to dashboard_path
  end

  private

  def select_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new_form.html.erb
<div class="d-flex justify-content-center" id='friend-booking-dates' data-unavailable="<%= friend.unavailable_dates.to_json %>">
  <%= simple_form_for [ friend, booking ] do |f| %>
  <div class="row">
    <div class="col">
      <%= f.input :start_time, as: :string, type: :text %>
    </div>
    <div class="col">
      <%= f.input :end_time, as: :string, type: :text %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col">
      <%= f.submit "Book now", class: "btn btn-primary" %>
    </div>
  </div>
  <% end %>
</div>

app/views/bookings/bookings.html.erb
<div class="container align-items-center">
  <div class="row">
     <div class="col-sm-12 col-md-6">
       <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="..." >
        <div class="card-body ">
          <h5 class="card-title"><%= @booking.friend_id %></h5>
          <p class="card-text"><%= @booking.user_id %></p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><p>Age: <%= @booking.status %></p></li>
          <li class="list-group-item"><p>Location: <%= @booking.start_time %> in</li>
        </ul>
      </div>
  </div>
</div>

app/views/bookings/destroy.html.erb
destroy.html.erb

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <%= simple_form_for [ @friend, @booking ] do |f| %>
        <%= f.input :start_time %>
        <%= f.input :end_time %>
        <%= f.input :total_price %>

        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class=" container align-items-center mt-5 mb-5">

  <div class="text-center">
    <h2>Booking Details</h2>
  </div>
  <div class="row justify-content-md-center mt-3 mb-3">

    <div class="card">
     <%= cl_image_tag @booking.friend.photo.key, height: 300, width: 400, crop: :fill %>
   <!--  <img height="350" width="100" class="card-img-top" src="http://res.cloudinary.com/daqhmzr2j/image/upload/c_fill,h_350,w_350/emcxas671ze805h9vud48inb459m"> -->

    </div>

    <div class="col-md-6 flex-column justify-space-around">
      <div class="card mb-3 text-align-center">
        <div class="card-body">
          <h4 class="card-title text-center"><b><p>Booked with  <%= @booking.friend.name %></p></b></h4>
            <p>Booking Starts :  <%= @booking.start_time.strftime("#{@booking.start_time.day.ordinalize} %B %-l.%M%P") %></p>
            <p>Booking Ends : <%= @booking.end_time.strftime("#{@booking.start_time.day.ordinalize} %B %-l.%M%P")  %></p>
            <p>Total Session Cost :  <em>$<%= @booking.total_price %></em></p>
            <p>Friend listed by : <%= link_to @booking.friend.user.first_name + " " + @booking.friend.user.last_name , dashboard_path %></p>
        </div>
       </div>
      <div class="card border-info text-warning">
        <div class="card-body">
         <p class="card-title">Pending Confirmation</p>
         <p class="card-text">Please wait for approval....</p>
       </div>
      </div>
    </div>
  </div>
</div>

app/views/friends/_calender.html.erb
<%= month_calendar events: bookings do |date, bookings| %>
  <%= date.day %>
    <% bookings.each do |booking| %>
    <div>
      <%= icon('fas', 'ban m-1 2em') %>
    </div>
  <% end %>
<% end %>

app/views/friends/_form.html.erb
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@friend) do |f| %>
      <!--   <%= f.error_notification %> -->
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

       <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :location %>
          <%= f.input :photo, as: :file %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, { :class=>"btn btn-primary btn-lg btn-block" } %>
        </div>

      <% end %>
    </div>
  </div>

app/views/friends/_info_window.html.erb
<h2><%= friend.name %></h2>
<%= cl_image_tag friend.photo.key, height: 150, width: 200, crop: :fill, class: "card-img-top" %>
<br><br>
<p><%= friend.description %></p>
 <%= link_to "View", friend_path(friend), { :class=>"btn btn-primary btn-lg btn-block" } %>

app/views/friends/_review_list.html.erb
<h3 class="text-center mt-4 mb-2">Reviews</h3>
  <% @friend.reviews.each do |review| %>
      <div class="d-flex">
        <div class="flex-grow-0 flex-shrink-0 mr-3">
          <p>
            <% review.rating.times do %>
              <%= icon('fas', 'star m-1 2em') %>
            <% end %>
            <% (5 - review.rating).times do %>
              <%= icon('far', 'star m-1 2em') %>
            <% end %>
          </p>
        </div>
        <div>
          <p><%= "#{review.content}" %></p>
        </div>
      </div>
  <% end %>

app/views/friends/_search_bar.html.erb
<%= form_tag friends_path, method: :get, :class => 'd-flex' do %>
  <%= text_field_tag :query_attributes,
    params[:query_attributes],
    class: "form-control",
    placeholder: "Find a friend"
  %>
    <%= text_field_tag :query_location,
    params[:query_location],
    class: "form-control",
    placeholder: "Enter a location"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>
<br>

app/views/friends/_show_page_map.html.erb
<div id="map"
   style="width: 100%; height: 300px;"
   data-markers="<%= @markers.to_json %>"
   data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" class="m-3">
</div>

app/views/friends/edit.html.erb
<h1>Edit Friend</h1>

<%= render 'form', friend: @friend %>

app/views/friends/index.html.erb
<h1 class="text-center mt-2" style="color: black;">Find a friend for any occasion</h1>
<div class="">
  <%= render 'search_bar' %>
  <div id="map"
       style="width: 100%; height: 600px;"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <br>
  <div>
    <div class="cards-container d-flex flex-wrap justify-content-center">
  <% @friends.each do |friend| %>
      <div class="card mx-3 mb-3 shadow mb-5 bg-white rounded" style="width: 300px;">
        <%= cl_image_tag friend.photo.key, height: 350, width: 350, crop: :fill, class: "card-img-top" %>
        <div class="card-body">
          <div class="card-text-container">
            <h5 class="card-title"><%= friend.name %></h5>
            <p class="card-text"><%= friend.description %></p>
            <p class="card-text">$<%= friend.price %> per hour</p>
          <p> <i class="fas fa-map-marker"> </i> <%=  friend.location %></p>
          </div>
          <%= link_to "View", friend_path(friend), { :class=>"btn btn-primary btn-lg btn-block" } %>
        </div>
      </div>
    <% end %>
    <div class="card mx-3 mb-3 shadow mb-5 bg-white rounded">
    <div class="card-body">
      <h5 class="card-title">List a friend</h5>
      <p class="card-text">Have a friend you'd like to list?</p>
      <%= link_to "Add a friend", new_friend_path, { :class=>"btn btn-primary btn-lg btn-block" }  %>
    </div>
    </div>
  </div>
  </div>
</div>

app/views/friends/new.html.erb
<div class="container">
<h1 class="text-center">Add a new Friend listing:</h1>
<%= render 'form', friend: @friend %>

</div>

app/views/friends/show.html.erb
<div class="justify-content-center mt-3 d-flex container">
  <div class="row">
     <div class="col-sm-12 col-md-6">
       <div class="card">
        <%= cl_image_tag @friend.photo.key, height: 500, crop: :fill, class: "card-img-top"  %>
        <div class="card-body ">
          <h3 class="card-title"><%= @friend.name %></h3>
          <p class="card-text"><%= @friend.description  %></p>
        </div>
        <ul class="list-group">
          <li class="list-group-item">
            <p>Skills:</p>
            <div class="d-flex">
              <% @friend.skills.each do |skill| %>
                <h4>
                  <span class="badge badge-secondary ml-2 friend-badge"><%= skill.name %></span>
                </h4>
              <% end %>
            </div>
          </li>
          <li class="list-group-item">Price: $<%= @friend.price %>.00 per hour</li>
          <li class="list-group-item">Location: <%= @friend.location  %></li>
          <li class="list-group-item">
             <div class="text-center mt-3">
                <%= render 'review_list', friend: @friend %>
            </div>
          </li>
        </ul>
      </div>
    </div>
    <div class="col-sm-12 col-md-6">
      <div class="card">
        <div class="card-body">
          <%= render 'show_page_map' %>
          <%= render '/bookings/new_form', booking: @booking, friend: @friend %>
          <br>
          <%= render 'calender', bookings: @friend.bookings %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendr</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag asset_path('favicon.png') %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>

  <% if current_page? root_path %>
    <div class="landing-page">
  <% else %>
    <%= render 'shared/navbar' %>
    <div class="container">
  <!-- PUT this above the 'yield' -->
  <% end %>
  <%= yield %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </div>

</body>

</html>

app/views/pages/dashboard.html.erb
<h2 class="mt-3 text-center">My Profile</h2>
<div class="cards-container d-flex flex-wrap mt-5">
  <div class="card mx-3 mt-3" style="width: 500px;">
    <%= cl_image_tag(current_user.photo.key, crop: :fill, class: "card-img-top")  %>
    <div class="card-body">
      <div class="card-title">
        <h1><%= current_user.first_name %></h1>
      </div>
      <span class="card-detail">
      <h5><%= current_user.description %></h5>
        <%= link_to "Edit my profile", edit_user_profile_path(current_user), { :class=>"btn btn-primary btn-md rounded-pill" } %>
        <%= link_to "Edit my account details", edit_user_registration_path, { :class=>"btn btn-primary btn-md rounded-pill" } %>
    </div>
  </div>

  <div class="card align-items-center mt-3 mb-3" style="width: 450px; height:550px">
    <h2 class="mt-3">Upcoming bookings</h2>
     <div class="card-body">
       <div class="text-center mt-3">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Name</th>
              <th scope="col">Start Date</th>

            </tr>
          </thead>
          <tbody>
            <% num = 1  %>
            <% current_user.bookings.each do |booking|  %>
              <tr>
                <th scope="row"> <%= num  %></th>
                <td> <%= link_to "#{booking.friend.name}", booking_path(booking) %></td>
                <td><%= booking.start_time.strftime("#{booking.start_time.day.ordinalize} %B %-l.%M%P") %></td>
                <td></td>
              </tr>

              <% num += 1  %>
            <% end %>
          </tbody>
          </table>

       </div>
     </div>
  </div>
</div>

<div class="mb-3 mt-3 text-center">

<%= link_to "My Bookings - Details", my_bookings_path,  { :class=>"btn btn-primary btn-lg rounded-pill" }  %>
<%= link_to "My Friends Listings", my_listings_path,  { :class=>"btn btn-primary btn-lg rounded-pill" }   %>

</div>

app/views/pages/home.html.erb
<div class="d-flex">
  <div class="home-image" style = "height: 100vh; width: 70%; background-size: cover;">

  </div>

  <div style = "height: 100vh; width: 30%;" class= " text-center d-flex flex-column justify-content-center align-items-center landing-page-side-bar ">
    <h1>MATCH.</h1>
    <h1>CHAT.</h1>
    <h1>BE-FRIEND.</h1>
    <br>
    <%= link_to "Find a friend", friends_path, { :class=>"btn btn-primary" }   %>
    <br>
    <br>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      I'm in the wrong place, I have many
    </button>
  </div>
 <%= render 'components/modal' %>
 </div>

app/views/pages/my_bookings.html.erb
<h1 class="mt-3">Browse My Bookings</h1>

<div class="cards-container">
  <% @bookings.each do |booking| %>
  <div class="card mb-3 p-1" style="width: 1000px;">
    <div class="row no-gutters">

      <div class="col-md-3 my-auto">
        <div>

          <%= cl_image_tag booking.friend.photo.key, height: 200, width: 246, crop: :fill %>
        </div>
      </div>

      <div class="col-md-8">
        <div class="card-body d-flex justify-content-between">
          <div>
            <h5 class="card-title" style="font-size:30px;"><%= link_to "Booking with #{booking.friend.name}", booking_path(booking) %></h5>
            <p>Status : <%= booking.status.capitalize %></p>
            <p>Starts :  <%= booking.start_time.strftime("#{booking.start_time.day.ordinalize} %B %-l.%M%P") %></p>
            <p>Ends : <%= booking.end_time.strftime("#{booking.start_time.day.ordinalize} %B %-l.%M%P")  %></p>
          </div>

          <div class = "ml-5" style="margin-top: 7rem;">
            <%=  link_to "Leave a Review",  new_booking_review_path(booking), { :class=>"btn btn-primary rounded-pill align-items-center" }  %>
          </div>
        </div>

      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="text-center">
  <%= link_to "Back to the your dashboard", dashboard_path, { :class=>"btn btn-primary btn-lg mt-5 rounded-pill" } %>
</div>

app/views/pages/my_listings.html.erb
<h1 class="mt-3">Browse My friends</h1>

<div class="cards-container">
  <% @friends.each do |friend| %>

  <div class="card mb-3 p-1">
    <div class="row">
      <div class="col-4">
        <%= cl_image_tag friend.photo.key, height: 200, width: 246, crop: :fill, class: "img-fluid w-100 mb-3" %>
        <br>
        <h3 class="card-title px-2 text-center"><%= link_to friend.name, friend_path(friend) %></h3>
        <div class="d-flex justify-content-around">
          <%= link_to "Edit My Friend", edit_friend_path(friend), class: "btn btn-outline-warning btn-sm rounded-pill" %>
          <%= link_to "Delete Friend", friend_path(friend), method: :delete, class: "btn btn-outline-danger btn-sm rounded-pill" %>
        </div>
      </div>

      <div class="col-8">
        <div class="card-body">
              <h3 class="card-title pb-3 text-center">Bookings</h3>
          <div class="row">
            <% friend.bookings.each do |booking| %>
            <div class="col-6">
              <h5><%= booking.user.first_name + " " +booking.user.last_name %></h5>
              <p>Status : <%= booking.status.capitalize %></p>
              <p>Starts :  <%= booking.start_time.strftime("#{booking.start_time.day.ordinalize} %B %-l.%M%P") %></p>
              <p>Ends : <%= booking.end_time.strftime("#{booking.start_time.day.ordinalize} %B %-l.%M%P")  %></p>
              <%= link_to "See this booking", booking_path(booking), { :class=>"btn btn-primary btn-lg btn-block mt-5 rounded-pill" } %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% end %>
</div>

<div class="text-center">
  <%= link_to "Back to the your dashboard", dashboard_path, { :class=>"btn btn-primary btn-lg mt-5 rounded-pill" } %>
</div>

app/views/reviews/new.html.erb
  <div class="row justify-content-center mt-5">
      <div class="col-sm-12 col-md-6 mt-3 card">
        <h5 class="card-title text-center mt-3"><strong>Review</strong></h5>
           <div class="card-info">

      <%= simple_form_for [ @booking, @review ] do |f| %>
        <%= f.input :content %>
        <%= f.input :rating%>
        <%= f.submit :submit%>

      <% end %>
  </div>
    </div>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>F.R.I.E.N.D.R
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Dashboard", dashboard_path , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add a friend", new_friend_path, { :class=>"btn btn-primary rounded-pill ml-4" }  %>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(user), url: user_profile_path(user) do |f| %>
<!--   <%= f.error_notification %> -->
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.submit "Save Changes", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<%= simple_form_for @user, url: user_profile_path(params[:id]) do |f| %>
<!--   <%= f.error_notification %> -->
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
      <%= f.input :first_name %>
      <%= f.input :last_name %>
      <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.submit "Save Changes", class: "btn btn-primary" %>
  </div>

<% end %>